services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6060:5000
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    user: postgres
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
secrets:
  db-password:
    file: db/password.txt
